// <auto-generated/>

namespace TransparentValueObjects
{
    /// <summary>
    /// Represents the interface for <see cref="global::TransparentValueObjects.DefaultValueAugment"/>
    /// with members that the consumer has to implement to support the augment.
    /// </summary>
    internal interface IDefaultValue<out TValueObject, TInnerValue>
        where TValueObject : global::TransparentValueObjects.IValueObject<TInnerValue>
        where TInnerValue : notnull
    {
        /// <summary>
        /// Gets the default value for this value object.
        /// </summary>
        public static abstract TValueObject DefaultValue { get; }
    }
}