namespace TransparentValueObjects.PostInitializationOutput;

public static partial class Augments
{
    public static class DefaultEqualityComparerAugment
    {
        public const string Name = nameof(DefaultEqualityComparerAugment);
        public const string GlobalName = $"global::{Constants.Namespace}.{Name}";
        public const string HintName = $"{Name}.g.cs";

        public const string SourceCode = /*lang=csharp*/
$$"""
{{Constants.AutoGeneratedHeader}}

namespace {{Constants.Namespace}}
{
    /// <summary>
    /// Augment to enable support for a default equality comparer.
    /// </summary>
    {{Constants.CodeCoverageAttribute}}
    public sealed class {{Name}} : {{IAugment.GlobalName}} { }
}
""";
    }
}
