namespace TransparentValueObjects.PostInitializationOutput;

public static partial class Augments
{
    public static class EfCoreAugment
    {
        public const string Name = nameof(EfCoreAugment);
        public const string GlobalName = $"global::{Constants.Namespace}.{Name}";
        public const string HintName = $"{Name}.g.cs";

        public const string SourceCode = /*lang=csharp*/
$$"""
{{Constants.AutoGeneratedHeader}}

namespace {{Constants.Namespace}}
{
    /// <summary>
    /// Augment to enable support for EF Core model configuration by generting a
    /// <c>ValueConverter<TValueObject, TInnerValue></c> and a <c>ValueComparer<TValueObject></c>.
    /// </summary>
    /// <remarks>
    /// This requires <c>Microsoft.EntityFrameworkCore</c>.
    /// </remarks>
    {{Constants.CodeCoverageAttribute}}
    public sealed class {{Name}} : {{IAugment.GlobalName}} { }
}
""";
    }
}
