namespace TransparentValueObjects.PostInitializationOutput;

public static partial class Augments
{
    public static class JsonAugment
    {
        public const string Name = nameof(JsonAugment);
        public const string GlobalName = $"global::{Constants.Namespace}.{Name}";
        public const string HintName = $"{Name}.g.cs";

        public const string SourceCode = /*lang=csharp*/
$$"""
{{Constants.AutoGeneratedHeader}}

namespace {{Constants.Namespace}}
{
    /// <summary>
    /// Augment to enable JSON support by generting a JSON converter for the value object.
    /// </summary>
    /// <remarks>
    /// This only supports <c>System.Text.Json</c> at the moment.
    /// </remarks>
    {{Constants.CodeCoverageAttribute}}
    public sealed class {{Name}} : {{IAugment.GlobalName}} { }
}
""";
    }
}
