using Xunit;

namespace TransparentValueObjects.Tests.PostInitializationOutput.Augments;

public class DefaultEqualityComparerAugmentTests
{
    private const string Expected = /*lang=csharp*/
"""
// <auto-generated/>

namespace TransparentValueObjects
{
	/// <summary>
	/// Augment to enable support for a default equality comparer.
	/// </summary>
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage(Justification = "Auto-generated")]
	public sealed class DefaultEqualityComparerAugment : global::TransparentValueObjects.IAugment { }
}
""";

    [Fact]
    public void Test_Source()
    {
        TestHelpers.TestPostInitializationOutput("DefaultEqualityComparerAugment.g.cs", Expected);
    }
}
