using Xunit;

namespace TransparentValueObjects.Tests.PostInitializationOutput.Augments;

public class DefaultValueAugmentTests
{
    private const string Expected = /*lang=csharp*/
"""
// <auto-generated/>

namespace TransparentValueObjects
{
	/// <summary>
	/// Augment to enable support for a default value.
	/// </summary>
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage(Justification = "Auto-generated")]
	public sealed class DefaultValueAugment : global::TransparentValueObjects.IAugment { }
}
""";

    [Fact]
    public void Test_Source()
    {
        TestHelpers.TestPostInitializationOutput("DefaultValueAugment.g.cs", Expected);
    }
}
