// <auto-generated/>

namespace TransparentValueObjects
{
    /// <summary>
    /// Augment to enable support for a default value.
    /// </summary>
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage(Justification = "Auto-generated")]
    internal sealed class DefaultValueAugment : global::TransparentValueObjects.IAugment { }
}