// <auto-generated/>

namespace TransparentValueObjects
{
    /// <summary>
    /// Augment to enable support for EF Core model configuration by generting a
    /// <see cref="global::Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter{TModel,TProvider}"/>
    /// and a <see cref="global::Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer{T}"/>.
    /// </summary>
    /// <remarks>
    /// This requires <c>Microsoft.EntityFrameworkCore</c>.
    /// </remarks>
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage(Justification = "Auto-generated")]
    internal sealed class EfCoreAugment : global::TransparentValueObjects.IAugment { }
}