// <auto-generated/>

namespace TransparentValueObjects
{
    /// <summary>
    /// Augment to enable support for EF Core model configuration by generting a
    /// ValueConverter and a ValueComparer.
    /// </summary>
    /// <remarks>
    /// This requires <c>Microsoft.EntityFrameworkCore</c>.
    /// </remarks>
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage(Justification = "Auto-generated")]
    internal sealed class EfCoreAugment : global::TransparentValueObjects.IAugment { }
}