// <auto-generated/>

namespace TransparentValueObjects
{
    /// <summary>
    /// Augment to enable JSON support by generting a JSON converter for the value object.
    /// </summary>
    /// <remarks>
    /// This only supports <c>System.Text.Json</c> at the moment.
    /// </remarks>
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage(Justification = "Auto-generated")]
    internal sealed class JsonAugment : global::TransparentValueObjects.IAugment { }
}