using Xunit;

namespace TransparentValueObjects.Tests.PostInitializationOutput.Augments;

public class JsonAugmentTests
{
    private const string Expected = /*lang=csharp*/
"""
// <auto-generated/>

namespace TransparentValueObjects
{
    /// <summary>
    /// Augment to enable JSON support by generting a JSON converter for the value object.
    /// </summary>
    /// <remarks>
    /// This only supports <c>System.Text.Json</c> at the moment.
    /// </remarks>
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage(Justification = "Auto-generated")]
	public sealed class JsonAugment : global::TransparentValueObjects.IAugment { }
}
""";

    [Fact]
    public void Test_Source()
    {
        TestHelpers.TestPostInitializationOutput("JsonAugment.g.cs", Expected);
    }
}
