using System.Diagnostics.CodeAnalysis;
using Xunit;

namespace TransparentValueObjects.Tests.PostInitializationOutput;

[SuppressMessage("ReSharper", "InconsistentNaming")]
public class IAugmentTests
{
    private const string Expected = /*lang=csharp*/
"""
// <auto-generated/>

namespace TransparentValueObjects
{
	/// <summary>
	/// Marker interface for augments.
	/// </summary>
	public interface IAugment { }
}
""";

    [Fact]
    public void Test_Source()
    {
        TestHelpers.TestPostInitializationOutput("IAugment.g.cs", Expected);
    }
}
