// <auto-generated/>

namespace TransparentValueObjects
{
    /// <summary>
    /// Represents a value object.
    /// </summary>
    /// <remarks>
    /// This is the non-generic interface.
    /// </remarks>
    /// <seealso cref="IValueObject{TInnerValue}"/>
    internal interface IValueObject
    {
        /// <summary>
        /// Gets the type of the inner value.
        /// </summary>
        public static abstract global::System.Type InnerValueType { get; }
    }

    /// <summary>
    /// Represents a value object.
    /// </summary>
    /// <remarks>
    /// This is the generic interface.
    /// </remarks>
    /// <seealso cref="IValueObject"/>
    /// <typeparam name="TInnerValue">The type of the inner value.</typeparam>
    internal interface IValueObject<TInnerValue> : IValueObject where TInnerValue : notnull { }
}