// <auto-generated/>

namespace TransparentValueObjects
{
    /// <summary>
    /// Indicates that the struct is a value object.
    /// </summary>
    /// <typeparam name="TInnerValue">The type of the inner value.</typeparam>
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage(Justification = "Auto-generated")]
    [global::System.AttributeUsage(global::System.AttributeTargets.Struct)]
    internal class ValueObjectAttribute<TInnerValue> : global::System.Attribute
        where TInnerValue : notnull { }
}
