using Xunit;

namespace TransparentValueObjects.Tests.PostInitializationOutput;

public class ValueObjectAttributeTests
{
    private const string Expected = /*lang=csharp*/
"""
// <auto-generated/>

namespace TransparentValueObjects
{
	/// <summary>
	/// Indicates that the struct is a value object.
	/// </summary>
	/// <typeparam name="TInnerValue">The type of the inner value.</typeparam>
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage(Justification = "Auto-generated")]
	[global::System.AttributeUsage(global::System.AttributeTargets.Struct)]
	public class ValueObjectAttribute<TInnerValue> : global::System.Attribute
		where TInnerValue : notnull { }
}
""";

    [Fact]
    public void Test_Source()
    {
        TestHelpers.TestPostInitializationOutput("ValueObjectAttribute.g.cs", Expected);
    }
}
