using System.Diagnostics.CodeAnalysis;

namespace TransparentValueObjects.PostInitializationOutput;

[SuppressMessage("ReSharper", "InconsistentNaming")]
public static class IAugment
{
    public const string Name = nameof(IAugment);
    public const string GlobalName = $"global::{Constants.Namespace}.{Name}";
    public const string HintName = $"{Name}.g.cs";

    public const string SourceCode = /*lang=csharp*/
$$"""
{{Constants.AutoGeneratedHeader}}

namespace {{Constants.Namespace}}
{
    /// <summary>
    /// Marker interface for augments.
    /// </summary>
    internal interface {{Name}} { }
}
""";
}
